### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by shdudwns** [HmHmmHm/SpawningPool#2]
Tare da wannan peulgin haɗin sabar shi kada ta kasance abin da yake cikin matsala? Shin ƙasa yake iyaka maimaitawa na halitta da kuma dogon Iple ta photo ne mai dogon doeseo Multi-core capabilities har yanzu suna da rai?

**Comment by shdudwns** [comment]
@onebone @HelloWorld017 @Happysttim @MuhunKim @HmHmmHm

**Comment by HmHmmHm** [comment]
i'm sorry, i can't read your comment
can you re-write it to english?
